catalog/urls.py
from django.urls import path

from . import views

app_name = 'catalog'
urlpatterns = [
    path('triangle/', views.triangle, name='triangle'),
    path('person/', views.person_create, name='person_create'),
    path('person/<int:pk>/', views.person_update, name='person_update'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),

]

catalog/models.py
import datetime

from django.db import models
from django.utils.translation import gettext_lazy as _


class City(models.Model):
    city_name = models.CharField(max_length=200, unique=True)
    city_index = models.IntegerField(unique=True)

    def __str__(self):
        return self.city_name


class Article(models.Model):
    article_name = models.CharField(max_length=200)
    article_desc = models.TextField(max_length=1000, )

    def __str__(self):
        return self.article_name


class Client(models.Model):
    client_name = models.CharField(max_length=200)
    client_email = models.CharField(max_length=200)
    client_phone = models.CharField(max_length=200)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    article = models.ManyToManyField(Article)

    def __str__(self):
        return self.client_name


class Shipper(models.Model):
    sipper_name = models.CharField(max_length=200)
    city = models.OneToOneField(City, on_delete=models.CASCADE)

    def __str__(self):
        return self.sipper_name


class Person(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)

    def __str__(self):
        return self.last_name


class Logs(models.Model):
    class CMethod(models.TextChoices):
        GET = 'GE', _('Get request')
        HEAD = 'HE', _('Head request')
        POST = 'PO', _('Post request')
        PUT = 'PU', _('Put request')
        DELETE = 'DE', _('Delete request')
        CONNECT = 'CO', _('Connect request')
        OPTIONS = 'OP', _('Options request')
        TRACE = 'TR', _('Trace request')
        PATCH = 'PA', _('Path request')

    path = models.CharField(max_length=100)
    method = models.CharField(max_length=2, choices=CMethod.choices)
    timestamp = models.DateTimeField(datetime.datetime.now())
    values = models.JSONField(default=dict)

    def __str__(self):
        return self.path

catalog/forms.py
from catalog.models import Person

from django import forms
from django.forms import ModelForm


class Triangle(forms.Form):
    cathetus_1 = forms.FloatField(min_value=1)
    cathetus_2 = forms.FloatField(min_value=1)


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['first_name', 'last_name', 'email']

catalog/views.py
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PersonForm, Triangle
from .models import Person


def triangle(request):
    hypotenuse = None
    if 'submit' in request.GET:
        form = Triangle(request.GET)
        if form.is_valid():
            hypotenuse = (form.cleaned_data.get('cathetus_1')**2 + form.cleaned_data.get('cathetus_2')**2)**0.5
            return render(request, 'triangle.html', {'hypotenuse': hypotenuse})
    else:
        form = Triangle()
    return render(request, 'triangle.html', {'form': form})


def person_create(request):
    if request.method == 'POST':
        form = PersonForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('catalog:person_create')
    else:
        form = PersonForm()
    return render(request, 'create_person.html', {"form": form})


def person_update(request, pk):
    person = get_object_or_404(Person, pk=pk)
    if request.method == 'POST':
        form = PersonForm(request.POST, instance=person)
        if form.is_valid():
            obj = form.save()
            return redirect('catalog:person_update', obj.id)
    else:
        form = PersonForm(instance=person)
    return render(request, 'update_person.html', {'form': form})

catalog/templates/create_person.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Person</title>
</head>
<body>
<form action="{% url 'catalog:person_create' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><input type="submit" value="Create"></p>
</form>
</body>
</html>

catalog/templates/triangle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Triangle</title>
</head>
<body>
<form action="{% url 'catalog:triangle' %}" method="get" >
    {% if hypotenuse is None %}
    <h3>Input values of your cathetuses here:</h3><br>
        {{ form }}
        <input type="submit" name='submit' value="Ok">
    {% else %}
    <h3>Value of hypotenuse is: {{ hypotenuse }}</h3><br>
    <p>Thanks that choose our service</p>
    {% endif %}
</form>
</body>
</html>

catalog/templates/update_person.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Get person</title>
</head>
<body>
<form action="{% url 'catalog:person_update' form.instance.pk %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><input type="submit" value="Update"></p>
</form>
</body>
</html>